### ISSUE TITLE
Do we need to pass adapter.Env during request process time

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#821] opened 2017-06-15 00:23 UTC
When making Check and Report process calls to the adapters, should we pass the adapter.Env object ?

Comment from @ZackButcher 
I think we also need to include a adapter.Env parameter in the generated golang version (it doesn't make since in the gRPC version). ATM there's no way for an adapter to log while processing, since we tuck the logger behind Env in adapters.
The idea is that we could do something like embed the span from the current trace into the environment, and have env.Logger() produce logs that are attached to the trace, rather than the glog based logger implementation we use today. Just one example, but anything of that nature will change per request. #798

**Comment by ZackButcher** [comment] 2017-06-15 16:24
Closing as a dupe of https://github.com/istio/mixer/issues/820, which I filed just barely before you :P

**Closed by ZackButcher** 2017-06-15 16:24 UTC
