### ISSUE TITLE
linters.sh often fails when run locally

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#329] opened 2017-03-04 16:09 UTC
I'm unable to run linters.sh on my local changes anymore. It just produces the error;

 fatal: bad revision '^'

This is because the LAST_GOOD_GITSHA variable ends up being set to ^ for some reason. I can't quite figure out what the script is actually trying to do so that's as far as I got in diagnosing the problem...

Also, we should add the example directory tree to the set of directories we lint.

**Comment by douglas-reid** [comment] 2017-03-05 05:26
I believe this happens when you have no outstanding local commits. If you make some changes and commit, the bad revision should go away.

Obviously, if you want to run the linters _before_ you commit, then this doesn't help you. That should be fixed.

**Comment by douglas-reid** [comment] 2017-03-05 05:28
It seems like the `|| LAST_GOOD_GITSHA='HEAD^'` clause is not working as intended.

**Comment by douglas-reid** [comment] 2017-03-05 05:40
I think we want something like:

```shell
LAST_GOOD_GITSHA="$(git log master.. --pretty='%H'|tail -1)"
[[ -z $LAST_GOOD_GITSHA ]] && LAST_GOOD_GITSHA='HEAD'
LAST_GOOD_GITSHA=$LAST_GOOD_GITSHA^;
```

**Closed** 2017-03-07 22:28 UTC
